accountant/urls.py
from django.conf.urls import url

from accountant.views.misc import sms, recalculate_request, document_upload, \
    document_delete
from accountant.views.invoice_create_or_edit_view import InvoiceCreateOrEditView
from accountant.views.invoice_detail_view import InvoiceDetailView
from accountant.views.invoice_list_view import InvoiceListView
from accountant.views.account_detail_view import AccountDetailView
from accountant.views.income_list_view import IncomeListView
from accountant.views.expense_list_view import ExpenseListView
from accountant.views.account_list_view import AccountListView

urlpatterns = [
    url(r'^incomes/', IncomeListView.as_view(), name='income_list'),
    url(r'^accounts/(?P<pk>[0-9]+)/', AccountDetailView.as_view(), name='account_detail'),
    url(r'^accounts/', AccountListView.as_view(), name='account_list'),
    url(r'^incomes/', IncomeListView.as_view(), name='income_list'),
    url(r'^expenses/', ExpenseListView.as_view(), name='expense_list'),
    url(r'^invoices/add/', InvoiceCreateOrEditView.as_view(), name='invoice_create'),
    url(r'^invoices/(?P<pk>[0-9]+)/edit/', InvoiceCreateOrEditView.as_view(), name='invoice_edit'),
    url(r'^invoices/(?P<pk>[0-9]+)/', InvoiceDetailView.as_view(), name='invoice_detail'),
    url(r'^invoices/', InvoiceListView.as_view(), name='invoice_list'),
    url(r'^sms/', sms, name='sms'),
    url(r'^recalculate/', recalculate_request, name='recalculate'),
    url(r'^document/upload', document_upload, name='document_upload'),
    url(r'^document/(?P<pk>[0-9]+)/delete', document_delete, name='document_delete')
]

frekenbok/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

from django.conf import settings
from django.conf.urls.static import static

from .views import DashboardView


urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^admin/', admin.site.urls),
    url(r'^accountant/', include('accountant.urls', namespace='accountant')),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountant/models.py
import logging
import mimetypes
import os
from decimal import Decimal

from django.db import models, transaction
from django.db.models import Sum
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from djmoney.models.fields import CurrencyField
from treebeard.ns_tree import NS_Node


logger = logging.getLogger(__name__)


class Account(NS_Node):
    INCOME = 1
    EXPENSE = 2
    ACCOUNT = 3
    TYPES = (
        (INCOME, _('income')),
        (EXPENSE, _('expense')),
        (ACCOUNT, _('account')),
    )

    title = models.CharField(
        verbose_name=_('title'),
        max_length=255,
        blank=True)
    bank_title = models.CharField(
        verbose_name=_('title used by bank to identify account in messages anf reports'),
        max_length=255,
        blank=True,
    )

    type = models.IntegerField(
        verbose_name=_('type'),
        choices=TYPES)
    dashboard = models.BooleanField(
        verbose_name=_('display on dashboard'),
        default=False
    )

    opened = models.DateField(
        verbose_name=_('date of open'),
        null=True, blank=True, auto_now_add=True
    )
    closed = models.DateField(
        verbose_name=_('date of close'),
        null=True, blank=True
    )

    credentials = models.TextField(
        verbose_name=_('credentials'),
        blank=True
    )

    def get_absolute_url(self):
        return reverse('accountant:account_detail', kwargs={'pk': self.pk})

    @property
    def depth_dashes(self):
        """
        That's a sort of dirty hack, returns string with several m-dashes.
        Number of dashes is equal to depth level of account in tree.
        :return: string with dashes
        """
        return '— ' * (self.depth - 1)

    @property
    def depth_nbsp(self):
        """
        That's a sort of dirty hack, returns string with several non-broken
        spaces. Number of spaces is equal to depth level of account in tree.
        :return: string with dashes
        """
        return '\u00A0' * (self.depth - 1)

    @property
    def sorted_sheaves(self):
        """
        Property contains list of sheaves for the account, sorted buy currency
        in alphabetical order. Sheaf in base currency will be placed of first
        place if exists.
        :return:
        """
        result = list()
        for sheaf in self.sheaves.order_by('currency'):
            if sheaf.currency == settings.BASE_CURRENCY:
                result.insert(0, sheaf)
            else:
                result.append(sheaf)
        return result

    def recalculate_summary(self, atomic=True):
        def do():
            self.sheaves.all().delete()
            result = Transaction.objects.filter(account=self)\
                .filter(approved=True)\
                .values('currency')\
                .annotate(amount=Sum('amount'))\
                .order_by('currency')
            for item in result:
                Sheaf.objects.create(account=self,
                                     amount=item['amount'],
                                     currency=item['currency']).save()

        if atomic:
            with transaction.atomic():
                do()
        else:
            do()

    def summary_at(self, date):
        """
        method returns QuerySet with dictionaries with expected account summary
         for specified date (including that date) for this account and all
         child ones. Result is sorted by currency in alphabetical order.

        >>> account = Account.objects.get(pk=1)
        >>> account.summary_at(date.today())
        <QuerySet [{'currency': 'RUB', 'amount': Decimal('88891.50000')},
                   {'currency': 'USD', 'amount': Decimal('200.00000')}]>

        :param date: date of summary
        :return: dictionary with summary
        """
        return Transaction.objects.filter(account__in=self.get_tree(self))\
            .filter(date__lte=date)\
            .values('currency')\
            .annotate(amount=Sum('amount'))\
            .order_by('currency')

    def tree_summary(self):
        """
        method returns summary of all child accounts ordered by currency
        >>> account = Account.objects.get(pk=34)
        >>> account.tree_summary()
        <QuerySet [{'currency': 'GBP', 'amount': Decimal('99.00000')},
                   {'currency': 'RUB', 'amount': Decimal('89119.50000')},
                   {'currency': 'USD', 'amount': Decimal('281.00000')}]>

        :return: QuerySet with summary
        """
        return Sheaf.objects.filter(account__in=self.get_tree(self))\
            .values('currency')\
            .annotate(amount=Sum('amount')).order_by('currency')

    def __str__(self):
        return '{title} ({type})'.format(
            title=self.title,
            type=dict(self.TYPES)[self.type]
        )

    class Meta:
        verbose_name = _('account')
        verbose_name_plural = _('accounts')


class Sheaf(models.Model):
    account = models.ForeignKey(
        verbose_name=_('account'),
        to=Account,
        related_name='sheaves'
    )
    amount = models.DecimalField(
        verbose_name=_('sheaf'),
        max_digits=settings.MAX_DIGITS,
        decimal_places=settings.DECIMAL_PLACES
    )
    currency = CurrencyField(
        verbose_name=_('currency'),
        price_field='amount',
        default=settings.BASE_CURRENCY
    )

    def __str__(self):
        return '{amount} {currency} on {account}'.format(
            amount=self.amount,
            currency=self.currency,
            account=self.account
        )

    def __eq__(self, other):
        return type(other) == Sheaf and \
               self.account == other.account and \
               self.amount == other.amount and \
               self.currency == other.currency

    def __ne__(self, other):
        return not self.__eq__(other)

    class Meta:
        unique_together = ('account', 'currency')


class Invoice(models.Model):
    timestamp = models.DateTimeField(
        verbose_name=_('date and time')
    )

    comment = models.TextField(
        verbose_name=_('comment'),
        blank=True
    )

    user = models.ForeignKey(
        verbose_name=_('user'),
        to=User,
        blank=True,
        null=True
    )

    def get_absolute_url(self):
        return reverse('accountant:invoice_detail', kwargs={'pk': self.pk})

    def verify(self):
        """
        method calculates sum of all transactions of the invoice and returns
        QuerySet with currencies that has outstanding transactions.

        >>> invoice = Invoice.objects.get(pk=3)
        >>> invoice.verify()
        <QuerySet [{'amount': Decimal('70000.00000'), 'currency': 'RUB'}]>

        :return: QuerySet with amounts and currencies. Empty QuerySet can
         be thought as sign of verified invoice.
        """
        return Transaction.objects.filter(invoice=self)\
            .values('currency')\
            .annotate(amount=Sum('amount'))\
            .exclude(amount=0)

    @property
    def is_verified(self):
        return not bool(self.verify())

    @property
    def pnl(self):
        """
        Property contains grouped by currency sum of all transaction of this
         invoice applied to accounts with type Account.ACCOUNT. It's designed
         to give a point of the invoice: was it some income, some expense
         or just some transfer between own accounts.
        :return: QuerySet with amounts and currencies
        
        >>> invoice = Invoice.objects.get(pk=4)
        >>> invoice.verify()
        <QuerySet [{'amount': Decimal('-500.00000'), 'currency': 'RUB'}]>
        """
        return Transaction.objects\
            .filter(invoice=self)\
            .filter(account__type=Account.ACCOUNT)\
            .values('currency')\
            .annotate(amount=Sum('amount'))\
            .exclude(amount=0)\
            .order_by('currency')

    def __get_distinct_accounts_by_type(self, type: int):
        return Account.objects \
            .filter(transactions__invoice=self) \
            .filter(type=type) \
            .distinct()

    @property
    def incomes(self):
        """
        List of Account.INCOME accounts involved to this invoice
        """
        return self.__get_distinct_accounts_by_type(Account.INCOME)

    @property
    def expenses(self):
        """
        List of Account.EXPENSE accounts involved to this invoice
        """
        return self.__get_distinct_accounts_by_type(Account.EXPENSE)

    @property
    def accounts(self):
        """
        List of Account.ACCOUNT accounts involved to this invoice
        """
        return self.__get_distinct_accounts_by_type(Account.ACCOUNT)

    @property
    def income_transactions(self):
        return self.transactions.filter(account__in=self.incomes)

    @property
    def expense_transactions(self):
        return self.transactions.filter(account__in=self.expenses)

    @property
    def internal_transactions(self):
        return self.transactions.filter(account__in=self.accounts)

    def __str__(self):
        return _('Invoice dated by {timestamp}{comment}').format(
            timestamp=self.timestamp,
            comment=' ({})'.format(self.comment) if self.comment else ''
        )

    class Meta:
        ordering = ['-timestamp']


class Transaction(models.Model):
    UNITS = (
        ('pcs', _('pieces')),
        ('kg', _('kilos')),
        ('g', _('grams')),
        ('l', _('liters')),
        ('gal', _('gallons')),
        ('p', _('pounds'))
    )

    date = models.DateField(
        verbose_name=_('date')
    )
    approved = models.BooleanField(
        verbose_name=_('approved'),
        default=True
    )

    account = models.ForeignKey(
        verbose_name=_('account'),
        to=Account,
        related_name='transactions'
    )

    amount = models.DecimalField(

accountant/views/account_detail_view.py
import logging
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Sum
from django.views.generic import DetailView

from accountant.models import Account, Transaction

logger = logging.getLogger(__name__)


class AccountDetailView(LoginRequiredMixin, DetailView):
    model = Account
    context_object_name = 'account'
    template_name = 'accountant/account_detail.html'

    def get_context_data(self, **kwargs):
        context = super(AccountDetailView, self).get_context_data(**kwargs)
        if context['account'].type == Account.ACCOUNT:
            context['account_list'] = \
                self.model.objects.filter(type=Account.ACCOUNT)\
                    .filter(Q(closed__gte=date.today()) | Q(closed=None)).all()
        context['transaction_list'] = \
            Transaction.objects.filter(account=self.object)\
                .order_by('-date')[:10]
        context['total_quantity'] = \
            Transaction.objects.filter(account=self.object)\
                .values('unit')\
                .annotate(quantity=Sum('quantity'))\
                .filter(quantity__isnull=False)\
                .order_by('quantity')
        return context

accountant/views/account_list_view.py
import logging
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import ListView

from accountant.models import Account

logger = logging.getLogger(__name__)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    context_object_name = 'account_list'
    template_name = 'accountant/account_list.html'

    def get_queryset(self):
        return self.model.objects.filter(type=Account.ACCOUNT) \
            .filter(Q(closed__gte=date.today()) | Q(closed=None))

accountant/views/expense_list_view.py
import logging
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import ListView

from accountant.models import Account

logger = logging.getLogger(__name__)


class ExpenseListView(LoginRequiredMixin, ListView):
    model = Account
    context_object_name = 'account_list'
    template_name = 'accountant/account_list.html'

    def get_queryset(self):
        return self.model.objects.filter(type=Account.EXPENSE) \
            .filter(Q(closed__gte=date.today()) | Q(closed=None))

accountant/views/income_list_view.py
import logging
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import ListView

from accountant.models import Account

logger = logging.getLogger(__name__)


class IncomeListView(LoginRequiredMixin, ListView):
    model = Account
    context_object_name = 'account_list'
    template_name = 'accountant/account_list.html'

    def get_queryset(self):
        return self.model.objects.filter(type=Account.INCOME) \
            .filter(Q(closed__gte=date.today()) | Q(closed=None))

accountant/views/invoice_detail_view.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView

from accountant.models import Invoice

logger = logging.getLogger(__name__)


class InvoiceDetailView(LoginRequiredMixin, DetailView):
    model = Invoice
    context_object_name = 'invoice'
    template_name = 'accountant/invoice_detail.html'

accountant/views/invoice_list_view.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from accountant.models import Invoice

logger = logging.getLogger(__name__)


class InvoiceListView(LoginRequiredMixin, ListView):
    model = Invoice
    context_object_name = 'invoice_list'
    template_name = 'accountant/invoice_list.html'
    paginate_by = 20

accountant/views/transaction_list_view.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from accountant.models import Transaction

logger = logging.getLogger(__name__)


class TransactionListView(LoginRequiredMixin, ListView):
    model = Transaction
    context_object_name = 'transaction'

accountant/templates/accountant/account_list.html
{% extends 'accountant/base.html' %}
{% load i18n %}
{% load humanize %}

{% block title %}{{ block.super }} — {% trans 'List of accounts' %}{% endblock %}

{% block x_title %}{% trans 'Account list' %}{% endblock %}

{% block x_content %}
<form action="{% url 'accountant:recalculate' %}" method="get" style="float: right">
<input class="btn btn-default" type="submit" value="{% trans 'Recalculate' %}">
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>{% trans 'Id' %}</th>
            <th>{% trans 'Title' %}</th>
            <th>{% trans 'Summary' %}</th>
            <th>{% trans 'Opened' %}</th>
            <th>{% trans 'Closed' %}</th>
        </tr>
    </thead>
    <tbody>
        {% for account in account_list %}
        <tr>
            <td><a href="{{ account.get_absolute_url }}">{{ account.id }}</a></td>
            <td><a href="{{ account.get_absolute_url }}">{{ account.depth_dashes }}{{ account.title }}</a></td>
            <td>{% for sheave in account.sorted_sheaves %}
                {{ sheave.amount|intcomma }} {{ sheave.currency }}<br />
                {% endfor %}</td>
            <td>{{ account.opened }}</td>
            <td>{% if account.closed %}{{ account.closed }}{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

accountant/templates/accountant/base.html
{% extends 'skeleton.html' %}
{% load i18n %}

{% block title %}{{ block.super }} — {% trans 'Accountant' %}{% endblock title %}

accountant/templates/accountant/invoice_create_or_edit.html
{% extends 'accountant/base.html' %}
{% load i18n %}
{% load l10n %}
{% load humanize %}

{% block title %}{{ block.super }} — {% trans 'Add invoice' %}{% endblock %}

{% block header_large %}{% trans 'Add new invoice' %}{% endblock %}

{% block x_content %}
<div class="col-md-12">
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <section class="panel">
    <div class="x_title"><h2>{% trans 'General info' %}</h2><div class="clearfix"></div></div>
    <div class="panel-body form-horizontal form-label-left">
      <div class="row">
        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="invoice-timestamp">{% trans 'Date and time' %}</label>
          <div class="col-md-6 col-sm-6 col-xs-12"><input type="text" id="invoice-timestamp" name="invoice-timestamp" required="required" class="form-control col-md-7 col-xs-12" value="{% if invoice %}{{ invoice.timestamp | date:'Y-m-d H:i:s' }}{% endif %}"></div>
        </div>
      </div>
      <div class="row">
        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="invoice-comment">{% trans 'Comment' %}</label>
          <div class="col-md-6 col-sm-6 col-xs-12"><input type="text" id="invoice-comment" name="invoice-comment" class="form-control col-md-7 col-xs-12" value="{% if invoice %}{{ invoice.comment }}{% endif %}"></div>
        </div>
      </div>
    </div>
  </section>
  <section class="panel">
    <div class="x_title"><h2>{% trans 'Transactions' %}</h2><div class="clearfix"></div></div>
    <div class="panel-body">
      {% for transaction in transactions %}
      <div class="row form-horizontal transaction">
        <input type="hidden" name="transaction-id" value="{{ transaction.id }}">
        <div class="col-md-2 col-sm-4 form-group has-feedback">
          <input type="text" class="form-control has-feedback-left" name="date" pattern="\d{4}-\d{2}-\d{2}" value="{{ transaction.date | date:'Y-m-d' }}">
          <span class="fa fa-calendar form-control-feedback left"></span>
        </div>
        <div class="col-md-2 col-sm-4"><input type="number" step="any" lang="en-150" class="form-control" name="amount" placeholder="{% trans 'amount' %}" value="{{ transaction.amount | unlocalize }}"></div>
        <div class="col-md-1 col-sm-4"><input type="text" class="form-control" name="currency" placeholder="{% trans 'currency' %}" value="{{ transaction.currency }}"></div>
        <div class="col-md-1"><input type="number" step="any" lang="en-150" class="form-control" name="quantity" placeholder="{% trans 'quantity' %}" value="{{ transaction.quantity | unlocalize }}"></div>
        <div class="col-md-1">
          <select class="select2_group form-control" name="unit">{% for unit in quantity_units %}
            <option value="{{ unit.0 }}"{% if transaction.unit == unit.0 %} selected="selected"{% endif %}>{{ unit.0 }}</option>{% endfor %}
          </select>
        </div>
        <div class="col-md-1"><input type="number" step="any" lang="en-150" class="form-control" name="price" placeholder="{% trans 'price' %}" value="{{ transaction.price | unlocalize }}"></div>
        <div class="col-md-2 col-sm-12"><input type="text" class="form-control" name="comment" placeholder="{% trans 'comment' %}" value="{{ transaction.comment }}"></div>
        <div class="col-md-2 col-sm-12">
          <select class="select2_group form-control" name="account">{% for account in accounts %}
            <option value="{{ account.id }}"{% if account.id == transaction.account_id %} selected="selected"{% endif %}>{{ account.depth_nbsp }}{{ account.title }}</option>{% endfor %}
          </select>
        </div>
      </div>
      {% endfor %}
      <div class="row form-horizontal transaction">
        <input type="hidden" name="transaction-id" value="">
        <div class="col-md-2 col-sm-4 form-group has-feedback">
          <input type="text" class="form-control has-feedback-left" name="date" pattern="\d{4}-\d{2}-\d{2}">
          <span class="fa fa-calendar form-control-feedback left"></span>
        </div>
        <div class="col-md-2 col-sm-4"><input type="number" step="any" lang="en-150" class="form-control" name="amount" placeholder="{% trans 'amount' %}"></div>
        <div class="col-md-1 col-sm-4"><input type="text" class="form-control" name="currency" placeholder="{% trans 'currency' %}" value="{{ base_currency }}"></div>
        <div class="col-md-1"><input type="number" step="any" lang="en-150" class="form-control" name="quantity" placeholder="{% trans 'quantity' %}"></div>
        <div class="col-md-1">
          <select class="select2_group form-control" name="unit">
            <option value=""></option>{% for unit in quantity_units %}
            <option value="{{ unit.0 }}">{{ unit.0 }}</option>{% endfor %}
          </select>
        </div>
        <div class="col-md-1"><input type="number" step="any" lang="en-150" class="form-control" name="price" placeholder="{% trans 'price' %}"></div>
        <div class="col-md-2 col-sm-12"><input type="text" class="form-control" name="comment" placeholder="{% trans 'comment' %}"></div>
        <div class="col-md-2 col-sm-12">
          <select class="select2_group form-control" name="account">{% for account in accounts %}
            <option value="{{ account.id }}">{{ account.depth_nbsp }}{{ account.title }}</option>{% endfor %}
          </select>
        </div>
      </div>
    </div>
  </section>
  <section class="panel">
    <div class="x_title"><h2>{% trans 'Documents' %}</h2><div class="clearfix"></div></div>
    <div class="panel-body">
      <table class="table" id="documents-table">
        <tr>
          <th>{% trans 'File name' %}</th>
          <th>{% trans 'Description' %}</th>
          <th></th>
        </tr>
        {% for document in documents %}
          <tr>
            <td>{{ document.file_name }}</td>
            <td>{{ document.description }}</td>
            <td><a href="{% url 'accountant:document_delete' pk=document.id %}"><span class="fa fa-close" style="color: #d9534f"></span></a></td>
          </tr>
        {% endfor %}
      </table>
      <div id="documentDropzone" class="dropzone"></div>
    </div>
  </section>
    <input class="btn btn-default" type="submit" value="{% trans 'Save' %}">
  </form>
</div>
{% endblock x_content %}

{% block inline-js %}
<script language="JavaScript">
  function getField(row, fieldName) {
    return row.find('[name=' + fieldName + ']');
  }

  function priceUpdated() {
    var row = jQuery(this).parent().parent();
    var amount = getField(row, 'amount');
    var quantity = getField(row, 'quantity');
    var price = getField(row, 'price');

    if (quantity.val()) {
      amount.val(quantity.val() * price.val());
      amount.change();
    } else if (amount.val()) {
      quantity.val(amount.val() / price.val());
    }
  }

  function amountUpdated() {
    var row = jQuery(this).parent().parent();
    var amount = getField(row, 'amount');
    var quantity = getField(row, 'quantity');
    var price = getField(row, 'price');

    if (quantity.val()) {
      price.val(amount.val() / quantity.val());
    } else if (price.val()) {
      quantity.val(amount.val() / price.val());
    }
  }

  function quantityUpdated() {
    var row = jQuery(this).parent().parent();
    var amount = getField(row, 'amount');
    var quantity = getField(row, 'quantity');
    var price = getField(row, 'price');

    if (amount.val()) {
      price.val(amount.val() / quantity.val());
    } else if (price.val()) {
      amount.val(quantity.val() * price.val());
      amount.change();
    }
  }

  function addTransaction() {
    var lastTransaction = jQuery('.transaction:last');
    var newTransaction = lastTransaction.clone(true);

    lastTransaction
      .on('change', '[name=amount]', amountUpdated)
      .on('change', '[name=price]', priceUpdated)
      .on('change', '[name=quantity]', quantityUpdated);
    if (lastTransaction.find('[name=date]').val() === '') {
      lastTransaction.find('[name=date]').val(moment(jQuery('#invoice-timestamp').val()).format('YYYY-MM-DD'))
    }

    if (lastTransaction.find('[name=currency]').val() === '') {
      lastTransaction.find('[name=currency]').val('{{ base_currency }}')
    }

    newTransaction.find('input').val('');
    newTransaction.insertAfter(lastTransaction);
  }

  jQuery('.transaction')
    .on('change', '[name=amount]', amountUpdated)
    .on('change', '[name=price]', priceUpdated)
    .on('change', '[name=quantity]', quantityUpdated);
  jQuery('.transaction:last').on('change', '[name=amount]', addTransaction);

  var invoiceTimestamp = jQuery('#invoice-timestamp');
  if (invoiceTimestamp.val() === '') {
    invoiceTimestamp.val(moment().format('YYYY-MM-DD HH:mm'))
  }

  var documentDropzone = new Dropzone('#documentDropzone', {
      paramName: 'document',
      url: '{% url 'accountant:document_upload' %}',
      headers: {
        'X-CSRFToken': Cookies.get('csrftoken')
      }
  });
  documentDropzone.on('success', function (file, response) {
      jQuery('<input type="hidden" value="' + response.id + '" name="document">').insertAfter('#documentDropzone');
  })
</script>
{% endblock %}

accountant/templates/accountant/invoice_list.html
{% extends 'accountant/base.html' %}
{% load i18n %}
{% load humanize %}

{% block title %}{{ block.super }} — {% trans 'List of invoices' %}{% endblock %}

{% block header_large %}{% trans 'Invoice list' %}{% endblock %}
{% block title_right %}<a href="{% url 'accountant:invoice_create' %}" class="btn btn-default">{% trans 'Add invoice' %}</a>{% endblock %}

{% block x_title %}{% trans 'Invoices' %}{% endblock x_title %}

{% block x_content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th>{% trans 'Date' %}</th>
            <th>{% trans 'User' %}</th>
            <th width="70%">{% trans 'Comment' %}</th>
            <th>{% trans 'P&L' %}</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for invoice in invoice_list %}
        <tr>
            <td><a href="{% url 'accountant:invoice_detail' invoice.id %}">{{ invoice.timestamp | date:'Y-m-d&\\n\\b\\s\\p;H:i:s' | safe }}</a></td>
            <td>{% if invoice.user %}{{ invoice.user }}{% else %}—{% endif %}</td>
            <td><a href="{% url 'accountant:invoice_detail' invoice.id %}">{{ invoice.comment }}</a></td>
            <td>{% if invoice.pnl %}{% for item in invoice.pnl %}{{ item.amount }} {{ item.currency }}{% endfor %}{% else %}—{% endif %}</td>
            <td>{% if invoice.is_verified %}<span class="fa fa-check"></span>{% else %}<span class="fa fa-close" style="color: #d9534f"></span>{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if is_paginated %}
<div class="paging_simple_numbers" id="pagination">
    <ul class="pagination">
        <li class="paginate_button previous{% if not page_obj.has_previous %} disabled{% endif %}"><a{% if page_obj.has_previous %} href="{% url 'accountant:invoice_list' %}?page={{ page_obj.previous_page_number }}"{% endif %}>«</a></li>
    {% for page_number in page_obj.paginator.page_range %}
        <li class="paginate_button{% if page_obj.number == page_number %} active{% endif %}"><a href="{% url 'accountant:invoice_list' %}?page={{ page_number }}">{{ page_number }}</a></li>
    {% endfor %}
        <li class="paginate_button next{% if not page_obj.has_next %} disabled{% endif %}"><a{% if page_obj.has_next %} href="{% url 'accountant:invoice_list' %}?page={{ page_obj.next_page_number }}"{% endif %}>»</a></li>
    </ul>
</div>
{% endif %}

{% endblock %}